site_name: HDFS学习笔记
pages:
    - Home: index.md
    - Java接口:
        - 读取数据: read_data.md
        - 写入数据: write_data.md
    - Configuration: Configuration.md
    - FileSystem: FileSystem.md
theme: readthedocs
